services:
  web:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        RUBY_VERSION: ${RUBY_VERSION:-3.0.4}
    working_dir: /workspace
    user: dev
    volumes:
      - .:/workspace
    ports:
      - "127.0.0.1:4000:4000"
    command: sh -lc "/home/dev/.rbenv/shims/bundle install && /home/dev/.rbenv/shims/bundle exec jekyll serve --host 0.0.0.0 --port 4000"
